### ISSUE TITLE
Releasing code

### ISSUE THREAD

**Issue by SylvainVerdy** [chufangao/TTM-RE#1]
Hello, 

I'd like to thank you for your work.
I would like to know when you could make the code available? 

Best regards, 
Sylvain

**Comment by chufangao** [comment]
Will try to do it by this weekend!

Sincerely,
Chufan Gao

**Comment by pidoux7** [comment]
Hello,
Very interesting work! 
Looking forward to see the code.

kind regards,
Guillaume

**Comment by chufangao** [comment]
Released, please let me know if there are any questions! Note that the performance varies slightly from paper due to inherent randomness.
