### ISSUE TITLE
train_revised的结果是怎么跑出的，有具体的脚本吗？

### ISSUE THREAD

**Issue by mkmkmk45** [chufangao/TTM-RE#2]
就是这个结果是怎么跑出的？TTM-RE 78.13±0.12 78.05±0.17 83.28±0.29 76.28±0.61 79.95±0.13 78.20±0.34 85.81±0.55 76.68±0.22

**Comment by chufangao** [comment]
Ah yes, I did not include the script to run that, but it should be the same as setting pretrain_distant=3 (which just directly finetunes ttm-re) in scripts/run_roberta_rank.sh

**Comment by mkmkmk45** [comment]
谢谢您的答复
