### ISSUE TITLE
Error in class DocREModel.forword() function

### ISSUE THREAD

**Issue by shiyunchengAI** [chufangao/TTM-RE#3]
I make pretrain_distant = 0, and i want a file named "pretrain_state_dict.pth".

model2.py demo:
        if labels is not None:
            labels = [torch.tensor(label) for label in labels]
            labels = torch.cat(labels, dim=0).to(self.args.device)

            for logits, loss_weight, m_tag in zip(logits_list, loss_weights_list, m_tags_list):

TypeError:
    for logits, loss_weight, m_tag in zip(logits_list, loss_weights_list, m_tags_list):
UnboundLocalError: local variable 'logits_list' referenced before assignment

**Comment by chufangao** [comment]
I have corrected this in the new version, marking this as closed. Let me know if there are further issues.
