### ISSUE TITLE
Incomplete code, can you provide additional information？

### ISSUE THREAD

**Issue by QQQ796** [chufangao/TTM-RE#4]
Hello author, I am very interested in your paper and code. However, there is no definition or explanation of "self.label_mu_extractor3" in ”model2.py“. Could you please provide a supplement? We look forward to your reply.

**Comment by chufangao** [comment]
Sorry, the code is certainly not the cleanest. For all purposes, please only look at the sections of the code starting from:

        if self.args.model_type == 'mse_dist3':

Will edit this to be clearer in the future. The other if statements were from other experiments that do not work as well as the method presented in the paper

**Comment by chufangao** [comment]
Edit: clarified the code in the new version
