### ISSUE TITLE
Get error when loading the released models

### ISSUE THREAD

**Issue by jiahao-cn** [chufangao/TTM-RE#5]
I tried to load "pretrain_state_dict.pth" or "finetune_state_dict.pth", but got "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory". Are the model files corrupted?

**Comment by chufangao** [comment]
I have reuploaded the files, apologies! Not sure why the previous version didn't work. Let me know if there is still an issue

**Comment by jiahao-cn** [comment]
The issue is resolved. Thank you !
