### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by ChenMo722** [chufangao/TTM-RE#6]
Hello, author, I am a beginner. When I run train2.py, an error occurs. The loss in line 90 is of type 'float', and loss. backward() requires a 'torch Tensor'. I tried using torch. sensor() to convert loss to 'torch Tensor', But it didn't work. How can I solve this problem?

**Comment by chufangao** [comment]
Did you just run train2.py? Can you try running the script: 

bash scripts/run_roberta_rank.sh

**Comment by ChenMo722** [comment]
Thank you, I tried running this script but encountered some new issues.
25248@□□ĩ MINGW64 /e/NLP_learning/TTM-RE-main
$ "E:\Program Files\Git\bin\sh.exe" E:/NLP_learning/TTM-RE-main/scripts/run_roberta_rank.sh
Traceback (most recent call last):
  File "E:\NLP_learning\TTM-RE-main\train2.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Please help me.
